CREATE DATABASE reviewComp;

\c reviewComp;

CREATE SCHEMA reviews;

CREATE TABLE hotels (
  id int GENERATED BY DEFAULT AS IDENTITY,
  hotel_name varchar(140) NOT NULL,
  hotel_city varchar(255) NOT NULL,
);

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY,
  username varchar(50) NOT NULL,
  user_avatar varchar(2083),
  user_city varchar(255) NOT NULL,
  user_contributions int DEFAULT 0,
  user_helpful_votes int DEFAULT 0,
);

CREATE TABLE reviews (
  id int GENERATED BY DEFAULT AS IDENTITY,
  user_id int NOT NULL references users(id),
  hotel_id int NOT NULL references hotels(id),
  review_date TIMESTAMP NOT NULL,
  review_body text(20000) NOT NULL,
  date_of_stay DATE NOT NULL,
  room_tip varchar(140),
  trip_type varchar(60),
  overall_rating tinyint NOT NULL,
  value_rating tinyint,
  location_rating tinyint,
  service_rating tinyint,
  rooms_rating tinyint,
  cleanliness_rating tinyint,
  sleep_quality_rating tinyint,
  review_helpful_votes int DEFAULT 0,
);